version: '3.9'

services:
  balancedb:
    container_name: balancedb
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - balancenw

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - balancedb
    networks:
      - balancenw
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}

volumes:
  pgdata:

networks:
  balancenw:

